openapi: 3.0.0
info:
  title: Traceability Schemas
  version: 1.0.0
servers:
  - url: https://w3id.org/traceability/openapi/components
  - url: http://localhost:3000/openapi/components

paths:
  allOf:
    - $ref: './paths/common.yml'
    - $ref: './paths/credentials.yml'
    - $ref: './paths/presentations.yml'
    - $ref: './paths/workflows.yml'
