$linkedData:
  term: ProductRegistrationEvidenceDocument
  '@id': https://w3id.org/traceability#ProductRegistrationEvidenceDocument
title: Product Registration Evidence Document
description: Evidence data for a registered eCommerce Product
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - ProductRegistrationEvidenceDocument
    default:
      - ProductRegistrationEvidenceDocument
    items:
      type: string
      enum:
        - ProductRegistrationEvidenceDocument
  category:
    title: A category for the product item.
    type: string
    default: ''
    $linkedData:
      term: category
      '@id': https://schema.org/category
  inProductGroupWithID:
    title: Indicates the productGroupID for a ProductGroup
    type: string
    default: ''
    $linkedData:
      term: inProductGroupWithID
      '@id': https://schema.org/inProductGroupWithID
  productID:
    title: Product ID
    type: string
    default: ''
    $linkedData:
      term: productID
      '@id': https://schema.org/productID
  mpn:
    title: Manufacturer Part Number (MPN)
    type: string
    default: ''
    $linkedData:
      term: mpn
      '@id': https://schema.org/mpn
  gtin:
    title: Global Trade Item Number (GTIN)
    type: string
    default: ''
    $linkedData:
      term: gtin
      '@id': https://schema.org/gtin
  isAccessoryOrSparePartFor:
    title: Is accessory or sparepart for
    type: string
    default: ''
    $linkedData:
      term: isAccessoryOrSparePartFor
      '@id': https://schema.org/isAccessoryOrSparePartFor
  releaseDate:
    title: Release date of a product or product model
    type: string
    default: ''
    $linkedData:
      term: releaseDate
      '@id': https://schema.org/releaseDate
  manufacturer:
    title: Manufacturer name or brand of the product
    type: string
    default: ''
    $linkedData:
      term: manufacturer
      '@id': https://schema.org/manufacturer
  globalLocationNumber:
    title: Global Location Number (GLN)
    default: ''
    description: >-
      A Global Location Number of the manufacturer issued by GS1 (required), for
      more information see http://www.gs1.org/gln.
    type: string
    $linkedData:
      term: globalLocationNumber
      '@id': https://schema.org/globalLocationNumber
  leiCode:
    title: Global Location Number (GLN)
    default: ''
    description: >-
      A Legal Entity Identifier of the manufacturer issued by GLEIF (required),
      for more information see https://gleif.org
    type: string
    $linkedData:
      term: leiCode
      '@id': https://schema.org/leiCode
  name:
    title: Name of the product item
    type: string
    default: ''
    $linkedData:
      term: name
      '@id': https://schema.org/name
  description:
    title: Description of the product item
    type: string
    default: ''
    $linkedData:
      term: description
      '@id': https://schema.org/description
  model:
    title: Model of the product
    type: string
    default: ''
    $linkedData:
      term: model
      '@id': https://schema.org/model
  color:
    title: Color of the product
    type: string
    default: ''
    $linkedData:
      term: color
      '@id': https://schema.org/color
  material:
    title: Material the product is made from
    type: string
    default: ''
    $linkedData:
      term: material
      '@id': https://schema.org/material
  weight:
    title: Weight of the product
    type: string
    default: ''
    $linkedData:
      term: weight
      '@id': https://schema.org/weight
  height:
    title: Height of the product
    type: string
    default: ''
    $linkedData:
      term: height
      '@id': https://schema.org/height
  width:
    title: Width of the product
    type: string
    default: ''
    $linkedData:
      term: width
      '@id': https://schema.org/width
  depth:
    title: Depth of the Product
    type: string
    default: ''
    $linkedData:
      term: depth
      '@id': https://schema.org/depth
  url:
    title: Url or the product item
    type: string
    default: ''
    $linkedData:
      term: url
      '@id': https://schema.org/url
  isBasedOn:
    title: Is based on
    type: string
    default: ''
    $linkedData:
      term: isBasedOn
      '@id': https://schema.org/isBasedOn
  image:
    title: Image of the product
    type: string
    default: ''
    $linkedData:
      term: image
      '@id': https://schema.org/image
additionalProperties: false
required:
  - type
  - category
  - inProductGroupWithID
  - productID
  - mpn
  - gtin
  - isAccessoryOrSparePartFor
  - releaseDate
  - manufacturer
  - globalLocationNumber
  - leiCode
  - name
  - description
  - model
  - color
  - material
  - weight
  - height
  - width
  - depth
  - url
  - isBasedOn
  - image
example: |-
  {
    "type": ["ProductRegistrationEvidenceDocument"],
    "category": "Specialty Goods",
    "inProductGroupWithID": "Group537",
    "productID": "58H7E5MR18",
    "mpn": "RI2GNK0VTV",
    "gtin": "17552493072510",
    "isAccessoryOrSparePartFor": "n/a",
    "releaseDate": "2020-01-07",
    "manufacturer": "Larkin - Armstrong",
    "globalLocationNumber": "3353436169913",
    "leiCode": "",
    "name": "Intelligent Granite Cheese",
    "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    "model": "b958ba42-ca02-44c7-90b2-0e6fbb34c4aa",
    "color": "plum",
    "material": "Wooden",
    "weight": "4.182 kg",
    "height": "9.535 m",
    "width": "5.342 m",
    "depth": "3.023 m",
    "url": "https://example.com/Intelligent Granite Cheese",
    "isBasedOn": "Generic Frozen Shoes",
    "image": "http://placeimg.com/640/480"
  }
