$linkedData:
  term: ProductReceiptRegistrationCredential
  '@id': https://w3id.org/traceability#ProductReceiptRegistrationCredential
title: Product Receipt Registration Credential
description: Ecommerce Product Receipt Registration Credential
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - ProductReceiptRegistrationCredential
    default:
      - ProductReceiptRegistrationCredential
    items:
      type: string
      enum:
        - ProductReceiptRegistrationCredential
  receiptID:
    title: receiptID
    description: >-
      The receipt number issued by a shipper/carrier receiving product to be
      packaged and shipped
    type: string
    $linkedData:
      term: receiptID
      '@id': >-
        https://w3id.org/traceability#ProductReceiptRegistrationCredential
  packingListID:
    title: packingListID
    description: The packing list VC IDs issues by the seller
    type: array
    items:
      type: string
    $linkedData:
      term: packingListID
      '@id': https://schema.org/identifier
  orderID:
    title: orderID
    description: The seller specific Order VC IDs
    type: array
    items:
      type: string
    $linkedData:
      term: orderID
      '@id': https://schema.org/orderNumber
  productInOrder:
    title: productInOrder
    description: Product VC IDs included in the packing list
    type: array
    items:
      type: string
    $linkedData:
      term: productInOrder
      '@id': https://schema.org/productID
  certificateName:
    title: certificateName
    description: Specific name of issued invoice registration certificate
    type: string
    $linkedData:
      term: certificateName
      '@id': https://schema.org/name
additionalProperties: false
required:
  - receiptID
  - packingListID
  - orderID
  - productInOrder
  - certificateName
example: |-
  {
    "type": ["ProductReceiptRegistrationCredential"],
    "receiptID": "Receipt#663",
    "packingListID": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a"
    ],
    "orderID": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a"
    ],
    "productInOrder": [
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58599e",
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
    ],
    "certificateName": "ACME Carrier Product Receipt Registration Certificate"
  }
