$linkedData:
  term: USDAPPQ587PlantImportApplication
  '@id': https://w3id.org/traceability#USDAPPQ587PlantImportApplication
title: USDA PPQ 587 Application for Permit to Import Plants or Plant Products
description: USDA APHIS (Animal and Plant Health Inspection Service) PPQ (Plant Protection and Quarantine) 587, Application for Permit to Import Plants or Plant Products.
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - USDAPPQ587PlantImportApplication
    default:
      - USDAPPQ587PlantImportApplication
    items:
      type: string
      enum:
        - USDAPPQ587PlantImportApplication
  applicant:
    title: Applicant
    description: Details regarding the person responsible for the importation. Applicant must be a United States resident. Include the organization name and address, if applicable.
    $ref: ./Person.yml
    $linkedData:
      term: applicant
      '@id': https://vocabulary.uncefact.org/associatedParty
  plantProductsImported:
    title: Plants or Plant Products to be Imported
    description: Details regarding the plants or plant products to be imported
    type: array
    items:
      $ref: ./AgricultureProduct.yml
    $linkedData:
      term: plantProductsImported
      '@id': https://vocabulary.uncefact.org/specifiedProduct
  intendedUse:
    title: Intended Use
    description: 'The intended use for these plants or plant products, such as: "Plants for planting (Nursery stock)"; "Small lots of seed"; "Fruit and vegetables"; or other.'
    type: string
    $linkedData:
      term: intendedUse
      '@id': https://vocabulary.uncefact.org/intendedUse
  meansOfTransportation:
    title: Means of Transportation
    description: 'The means of transportation for these plants or plant products, such as: "Mail or Express carrier"; "Cargo shipment"; "Personal baggage or car"; or other.'
    type: string
    $linkedData:
      term: meansOfTransportation
      '@id': https://vocabulary.uncefact.org/usedTransportMeans
  date:
    title: Date
    description: The date of completion for this application.
    type: string
    $linkedData:
      term: date
      '@id': https://vocabulary.uncefact.org/creationDateTime
additionalProperties: false
required:
  - type
example: |-
  {
    "type": ["USDAPPQ587PlantImportApplication"],
    "applicant": {
      "type": [
        "Person"
      ],
      "firstName": "Jocelyn",
      "lastName": "Grates",
      "email": "jgrates@example.com",
      "phoneNumber": "+1-460-555-4373",
      "worksFor": {
        "type": [
          "Organization"
        ],
        "name": "New Fields Foodstuff logistics",
        "description": "Agricultural goods distribution",
        "email": "contact@example.net",
        "phoneNumber": "+1-521-555-6143",
        "faxNumber": "+1-150-555-7668"
      },
      "jobTitle": "Principal Data Supervisor"
    },
    "plantProductsImported": [
      {
        "type": [
          "AgricultureProduct"
        ],
        "upc": "033383401508",
        "plu": "94225",
        "gtin": "033383401508",
        "countryOfOrigin": "United States",
        "product": {
          "type": [
            "Product"
          ],
          "manufacturer": {
            "type": [
              "Organization"
            ],
            "email": "Ashlee.Grady@example.net",
            "phoneNumber": "+1-899-555-1399"
          },
          "name": "Avocados",
          "description": "Avocados, 4 pack boxes",
          "sizeOrAmount": {
            "type": [
              "QuantitativeValue"
            ],
            "unitCode": "hg/ha",
            "value": "60"
          },
          "weight": {
            "type": [
              "QuantitativeValue"
            ],
            "unitCode": "hg/ha",
            "value": "6960"
          },
          "sku": "81055399441"
        },
        "plantParts": "fruit",
        "scientificName": "Persea americana",
        "labelImageUrl": "https://img.example.org/033383401508/640/480/",
        "labelImageHash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "name": "Avocados",
        "productImageUrl": "https://img.example.org/102934920857/937/903/",
        "productImageHash": "8kb47j986hklhde4rfh78okjhgjo08765fgu7tfg4t864fy876rfser45thj87f3"
      }
    ],
    "intendedUse": "Fruits and vegetables",
    "meansOfTransportation": "Cargo shipment",
    "date": "2022-08-10"
  }
