$linkedData:
  term: Workflow
  '@id': https://w3id.org/traceability#Workflow
title: Workflow
description: A workflow instance and definition. 
type: object
properties:
  type:
    oneOf:
      - type: array
        items:
          type: string
          enum:
            - Workflow
      - type: string
        const:
          - Workflow
  definition: 
    description: Identifier of a particular type of workflow. 
    type: array
    items:
      type: string
  instance:
    description: Identifier of an instance of a workflow type. 
    type: array
    items:
      type: string
example: |-
  {
    "type": "Workflow",
    "definition": [
      "urn:uuid:n1552885-cc91-4bb3-91f1-5466a0be084e"
    ],
    "instance": [
      "urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
    ]
  }