title: workflow
description: This is a property of a TraceablePresentation, and receives its semantics from that RDF Class.
type: object
properties:
  definition: 
    description: The Workflow Definition indicates the intention behind the presentation. 
    type: array
    items:
      type: string
  instance:
    description: The Workflow Instance identifies this particular workflow. Subsequent presentations may indicate correlation by referencing the same instance identifier.
    type: array
    items:
      type: string
additionalProperties: false  
required:
  - instance
example: |-
  {
    "definition": [
      "https://w3id.org/traceability/#sima-steel-license"
    ],
    "instance": [
      "urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
    ]
  }