$linkedData:
  term: Workflow
  '@id': https://w3id.org/traceability#Workflow
title: Workflow
description: A Workflow Definition and Instance.
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - Workflow
    default:
      - Workflow
    items:
      type: string
      enum:
        - Workflow
  definition: 
    description: The Workflow Definition indicates the intention behind the presentation. 
    type: array
    items:
      type: string
    $linkedData:
      term: definition
      '@id': https://w3id.org/traceability/#workflow-definition
  instance:
    description: The Workflow Instance identifies this particular workflow. Subsequent presentations may indicate correlation by referencing the same instance identifier.
    type: array
    items:
      type: string
    $linkedData:
      term: instance
      '@id': https://w3id.org/traceability/#workflow-instance
additionalProperties: false  
required:
  - instance
example: |-
  {
    "type": [
      "Workflow"
    ],
    "definition": [
      "https://w3id.org/traceability/#sima-steel-license"
    ],
    "instance": [
      "urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
    ]
  }