$linkedData:
  term: SIMASteelImportLicense
  '@id': https://w3id.org/traceability#SIMASteelImportLicense
title: SIMA Steel Import License
description: SIMA Steel Import License
type: object
properties:
  type:
    oneOf:
      - type: array
      - type: string
        enum:
          - SIMASteelImportLicense
  applicantCompany:
    title: Applicant Company
    description: Company responsible for shipment
    $ref: ./Organization.yml
    $linkedData:
      term: applicantCompany
      '@id': https://schema.org/Organization
  customsEntryNumber:
    title: Customs Entry Number
    description: Input if known at time of application. This number is optional.
    type: string
    $linkedData:
      term: customsEntryNumber
      '@id': https://schema.org/identifier
  importer:
    title: Importer
    description: Name of Importer of Record.
    $ref: ./Organization.yml
    $linkedData:
      term: importer
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#importerParty
  exporter:
    title: Exporter
    description: Name of Exporter.
    $ref: ./Organization.yml
    $linkedData:
      term: exporter
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#exporterParty
  manufacturer:
    title: Manufacturer
    description: Name of manufacturer(s) of the product(s) or shipper(s). May list multiple manufacturers or as unknown.
    type: array
    items:
      $ref: ./Organization.yml
    $linkedData:
      term: manufacturer
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#manufacturerParty  
  countryOfOrigin:
    title: Country of Origin
    description: Country in which the product(s) were manufactured. The two-letter ISO 3166-1 alpha-2 country code.
    type: string
    $linkedData:
      term: countryOfOrigin
      '@id': https://schema.org/addressCountry
  countryOfExportation:
    title: Country of Exportation
    description: Country from which the product(s) were exported. The two-letter ISO 3166-1 alpha-2 country code.
    type: string
    $linkedData:
      term: countryOfExportation
      '@id': https://schema.org/addressCountry
  expectedPortOfEntry: 
    title: Expected Port of Entry
    description: Expected port of entry. 
    type: string
    $linkedData:
      term: expectedPortOfEntry
      '@id': >-
        https://service.unece.org/trade/uncefact/vocabulary/uncefact/#UNECELOCODE
  expectedDateOfExport: 
    title: Expected Date of Export
    description: Date product(s) expected to be shipped from the country of exportation.
    type: string
    $linkedData:
      term: expectedDateOfExport
      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#exportExitDateTime
      '@type': http://www.w3.org/2001/XMLSchema#dateTime
  expectedDateOfImport: 
    title: Expected Date of Import
    description: Date product(s) expected to be shipped from the country of exportation.
    type: string
    $linkedData:
      term: expectedDateOfImport
      '@id': https://w3id.org/traceability#importDateTime
      '@type': http://www.w3.org/2001/XMLSchema#dateTime
  productInformation:
    title: Product Information
    description: Product information for each product.
    type: array
    items:
      $ref: ./SIMASteelImportProductSpecifier.yml
    $linkedData:
      term: productInformation
      '@id': https://w3id.org/traceability#SIMASteelImportProductSpecifier
additionalProperties: true
example: |-
  {
    "type": "SIMASteelImportLicense", 
    "applicantCompany": {
      "type": "Organization",
      "name": "Maxi Acero Mexicano",
      "description": "Fusión y fabricación de acero sólido",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "Avenida Carlos 100",
        "addressLocality": "Hernádez de Mara",
        "addressRegion": "Nuevo Leon",
        "postalCode": "32200",
        "addressCountry": "Mexico"
      },
      "email": "info@example.net",
      "phoneNumber": "555-127-7813"
    }, 
    "customsEntryNumber": "34001239", 
    "importer": {
      "type": "Organization",
      "name": "American Prime Steel Inc.",
      "description": "Quality Steel since 1952",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "1551 Keebler Knoll",
        "addressLocality": "Vivianeburgh",
        "addressRegion": "Oregon",
        "postalCode": "47090",
        "addressCountry": "US"
      },
      "email": "contact@example.net",
      "phoneNumber": "555-716-2400"
    }, 
    "exporter": {
      "type": "Organization",
      "name": "Maxi Acero Mexicano",
      "description": "Fusión y fabricación de acero sólido",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "Avenida Carlos 100",
        "addressLocality": "Hernádez de Mara",
        "addressRegion": "Nuevo Leon",
        "postalCode": "32200",
        "addressCountry": "Mexico"
      },
      "email": "info@example.net",
      "phoneNumber": "555-127-7813"
    }, 
    "manufacturer": [
      {
        "type": "Organization",
        "name": "Maxi Acero Mexicano",
        "description": "Fusión y fabricación de acero sólido",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "Avenida Carlos 100",
          "addressLocality": "Hernádez de Mara",
          "addressRegion": "Nuevo Leon",
          "postalCode": "32200",
          "addressCountry": "Mexico"
        },
        "email": "info@example.net",
        "phoneNumber": "555-127-7813"
      }
    ], 
    "countryOfOrigin": "MX", 
    "countryOfExportation": "MX", 
    "expectedPortOfEntry": "USMOB", 
    "expectedDateOfExport": "2021-07-02", 
    "expectedDateOfImport": "2021-07-06",
    "productInformation": [
      {
        "type": [
          "SIMASteelImportProductSpecifier"
        ],
        "steelProduct": {
          "type": "SteelProduct",
          "heatNumber": "841",
          "specification": "ASTM-66272",
          "grade": "95913",
          "originalCountryOfMeltAndPour": "MX",
          "weight": 3200,
          "weightUnit": "https://service.unece.org/trade/uncefact/vocabulary/rec20/#kilogram",
          "commodity": {
            "type": "Commodity",
            "commodityCode": "721320",
            "commodityCodeType": "HS",
            "description": "Steel Coils"
          }
        },
        "customsValue": 4450
      }
    ]
  }
