title: Workflow
type: object
description: A workflow instance and definition. 
  - type: object
    properties:
      definition: 
        description: Identifier of a particular type of workflow. 
        type: array
        items:
          type: string
      instance:
        description: Identifier of an instance of a workflow type. 
        type: array
        items:
          type: string
example:
  {
    "definition": [
      "n1552885-cc91-4bb3-91f1-5466a0be084e"
    ],
    "instance": [
      "f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
    ]
  }