$linkedData:
  term: NaturalGasProducerEnvironmentalPassportCredential
  '@id': https://w3id.org/traceability#NaturalGasProducerEnvironmentalPassportCredential
title: Natural Gas Producer Environmental Passport Credential
tags:
  - Oil and Gas
description: A credential that represents the environmental passport of a natural gas producer
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/ns/credentials/v2
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/ns/credentials/v2
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/ns/credentials/v2
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - NaturalGasProducerEnvironmentalPassportCredential
    default:
      - VerifiableCredential
      - NaturalGasProducerEnvironmentalPassportCredential
    items:
      type: string
      enum:
        - VerifiableCredential
        - NaturalGasProducerEnvironmentalPassportCredential
  id:
    type: string
    format: uri
  validFrom:
    type: string
    format: date-time
  validUntil:
    type: string
    format: date-time
  issuer:
    $ref: ../common/Organization.yml
  credentialSchema:
    type: object
    properties:
      id:
        title: Id
        description: The url of the schema file to validate the shape of the json object
        type: string
        format: uri
        example: https://w3id.org/traceability/openapi/components/schemas/credentials/NaturalGasProducerEnvironmentalPassportCredential.yml
        default: https://w3id.org/traceability/openapi/components/schemas/credentials/NaturalGasProducerEnvironmentalPassportCredential.yml
        readOnly: true
      type:
        title: Type
        description: The type of validation to be run against the defined schema
        const: OpenApiSpecificationValidator2022
  credentialSubject:
    title: Natural Gas Producer Environmental Passport Credential
    description: A credential that represents the environmental passport of a natural gas producer
    type: object
    properties:
      organization:
        type: object
        title: Organization
        description: the organization the passport is issued to
        properties:
          legalName:
            type: string
            title: Organization Legal Name
            description: Legal name of the Organization
          dailyVolumeProduced:
            type: string
            title: Daily volume produced
            description: Daily volume of Natural Gas produced in MMcf/d (Millions of cubic feet per day)
          productionLocation:
            type: object
            description: the location of the production site
            $ref: ../common/Place.yml
          productionPhase:
            type: string
            enum:
              - Active
              - Inactive
              - In development
        required:
          - legalName
          - dailyVolumeProduced
          - productionLocation
          - productionPhase
      certifications:
        title: Certifications
        type: array
        items:
          type: object
          properties:
            certificationPeriod:
              type: string
              format: date-time
              title: Certification Period
              description: the validity period of the certification
            certificateIssuer:
              type: string
              title: Certificate Issuer
              description: issuer of the certificate
            certificateIdentifier:
              type: string
              title: CertificateIdentifier
              description: the identifier of the certificate
            certificationStandard:
              type: string
              title: CertificationStardard
              description: the standard for the certification.
            assessmentBody:
              type: string
              title: Assessment Body
              description: The entity that conducts the assessment for the certification
            observations:
              title: Observations
              description: >-
                List of observations
              type: array
              items:
                $ref: ../common/Observation.yml
          required:
            - certificationPeriod
            - certificateIssuer
            - certificateIdentifier
            - certificationStandard
            - observations
  proof:
    $ref: ../snippets/proof.yml
additionalProperties: false
required:
  - '@context'
  - type
  - id
  - validFrom
  - issuer
  - credentialSubject
example: |-
  {
    "@context": [
      "https://www.w3.org/ns/credentials/v2",
      "https://w3id.org/traceability/v1"
    ],
    "id": "http://example.com/dd0c6f9a-5df6-40a3-bb34-863cd1fda606",
    "type": [
      "VerifiableCredential",
      "NaturalGasProducerEnvironmentalPassportCredential"
    ],
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:web:organization.example.com"
    },
    "validFrom": "2022-11-01T10:58:45-04:00",
    "credentialSubject": {
      "organization": {
        "legalName": "Example Company",
        "dailyVolumeProduced": "200",
        "productionLocation": {
          "type": [
            "Place"
          ],
          "globalLocationNumber": "1111111111111",
          "geo": {
            "type": [
              "GeoCoordinates"
            ],
            "latitude": "-79.6395",
            "longitude": "178.5353"
          },
          "address": {
            "type": [
              "PostalAddress"
            ],
            "name": "Example Production Location",
            "streetAddress": "100 main street",
            "addressLocality": "Example locality",
            "addressRegion": "Example Region",
            "postalCode": "1X2Y3Z",
            "addressCountry": "CA"
          },
          "unLocode": "DKCPH"
        },
        "productionPhase": "Active"
      },
      "certifications": [
        {
          "certificationPeriod": "2019-12-11T03:50:55Z",
          "certificateIssuer": "MiQ",
          "certificateIdentifier": "123456",
          "certificationStandard": "MiQ",
          "assessmentBody": "Example Body",
          "observations": [
            {
              "type": [
                "Observation"
              ],
              "date": "2019-12-11T03:50:55Z",
              "property": {
                "type": [
                  "ChemicalProperty"
                ],
                "name": "Methane Intensity"
              },
              "measurement": {
                "type": [
                  "MeasuredValue"
                ],
                "value": "00.00",
                "unitCode": "UNKNOWN"
              }
            }
          ]
        }
      ]
    }
  }