$linkedData:
  term: SIMASteelImportLicenseApplicationCertificate
  '@id': https://w3id.org/traceability#SIMASteelImportLicenseApplicationCertificate
title: SIMA Steel Import License Application Certificate
tags:
  - Steel
description: Steel Import Monitoring and Analysis Licensing Application based on https://www.trade.gov/us-industry-licensing.
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - SIMASteelImportLicenseApplicationCertificate
    default:
      - VerifiableCredential
      - SIMASteelImportLicenseApplicationCertificate
    items:
      type: string
      enum:
        - VerifiableCredential
        - SIMASteelImportLicenseApplicationCertificate
  id:
    type: string
  name:
    type: string
  description:
    type: string
  issuanceDate:
    type: string
  issuer:
    type: object
  credentialSubject:
    $ref: ../common/SIMASteelImportLicense.yml
  proof:
    type: object
  relatedLink:
    title: Related Link
    description: Links related to this verifiable credential
    type: array
    items:
      $ref: ../common/LinkRole.yml
additionalProperties: false
required:
  - '@context'
  - type
  - issuanceDate
  - issuer
  - credentialSubject
example: |-
  {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "did:key:z6MknrcKsbzfy6kKFxtJQHxq43zHofhBuUqB6QGvvqF6FX7c",
    "type": [
      "VerifiableCredential",
      "SIMASteelImportLicenseApplicationCertificate"
    ],
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "name": "Maxi Acero Mexicano",
      "description": "Fusión y fabricación de acero sólido",
      "location": {
        "type": [
          "Place"
        ],
        "address": {
          "type": [
            "PostalAddress"
          ],
          "streetAddress": "Avenida Carlos 100",
          "addressLocality": "Hernádez de Mara",
          "addressRegion": "Nuevo Leon",
          "postalCode": "32200",
          "addressCountry": "Mexico"
        }
      },
      "email": "info@example.net",
      "phoneNumber": "555-127-7813"
    },
    "issuanceDate": "2022-02-28T11:23:00Z",
    "credentialSubject": {
      "type": [
        "SIMASteelImportLicense"
      ],
      "applicantCompany": {
        "type": [
          "Organization"
        ],
        "name": "Maxi Acero Mexicano",
        "description": "Fusión y fabricación de acero sólido",
        "location": {
          "type": [
            "Place"
          ],
          "address": {
            "type": [
              "PostalAddress"
            ],
            "streetAddress": "Avenida Carlos 100",
            "addressLocality": "Hernádez de Mara",
            "addressRegion": "Nuevo Leon",
            "postalCode": "32200",
            "addressCountry": "Mexico"
          }
        },
        "email": "info@example.net",
        "phoneNumber": "555-127-7813"
      },
      "customsEntryNumber": "34001239",
      "importer": {
        "type": [
          "Organization"
        ],
        "name": "American Prime Steel Inc.",
        "description": "Quality Steel since 1952",
        "location": {
          "type": [
            "Place"
          ],
          "address": {
            "type": [
              "PostalAddress"
            ],
            "streetAddress": "1551 Keebler Knoll",
            "addressLocality": "Vivianeburgh",
            "addressRegion": "Oregon",
            "postalCode": "47090",
            "addressCountry": "US"
          }
        },
        "email": "contact@example.net",
        "phoneNumber": "555-716-2400"
      },
      "exporter": {
        "type": [
          "Organization"
        ],
        "name": "Maxi Acero Mexicano",
        "description": "Fusión y fabricación de acero sólido",
        "location": {
          "type": [
            "Place"
          ],
          "address": {
            "type": [
              "PostalAddress"
            ],
            "streetAddress": "Avenida Carlos 100",
            "addressLocality": "Hernádez de Mara",
            "addressRegion": "Nuevo Leon",
            "postalCode": "32200",
            "addressCountry": "Mexico"
          }
        },
        "email": "info@example.net",
        "phoneNumber": "555-127-7813"
      },
      "manufacturer": {
        "type": [
          "Organization"
        ],
        "name": "Maxi Acero Mexicano",
        "description": "Fusión y fabricación de acero sólido",
        "location": {
          "type": [
            "Place"
          ],
          "address": {
            "type": [
              "PostalAddress"
            ],
            "streetAddress": "Avenida Carlos 100",
            "addressLocality": "Hernádez de Mara",
            "addressRegion": "Nuevo Leon",
            "postalCode": "32200",
            "addressCountry": "Mexico"
          }
        },
        "email": "info@example.net",
        "phoneNumber": "555-127-7813"
      },
      "countryOfOrigin": "MX",
      "countryOfExportation": "MX",
      "countryOfMeltAndPour": "MX",
      "expectedPortOfEntry": "USMOB",
      "expectedDateOfExport": "2022-04-02T08:00:00Z",
      "expectedDateOfImport": "2022-04-09T10:30:00Z",
      "productInformation": [
        {
          "type": [
            "SIMASteelImportProductSpecifier"
          ],
          "steelProduct": {
            "type": [
              "SteelProduct"
            ],
            "heatNumber": "841",
            "specification": "ASTM-66272",
            "grade": [
              "95913"
            ],
            "originalCountryOfMeltAndPour": "MX",
            "weight": 3200,
            "weightUnit": "https://service.unece.org/trade/uncefact/vocabulary/rec20/#kilogram",
            "commodity": {
              "type": [
                "Commodity"
              ],
              "commodityCode": "721320",
              "commodityCodeType": "HS",
              "description": "Steel Coils"
            }
          },
          "customsValue": 4450
        }
      ]
    },
    "proof": {
      "type": "Ed25519Signature2018",
      "created": "2022-10-11T17:05:33Z",
      "verificationMethod": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U#z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "proofPurpose": "assertionMethod",
      "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..4aQ3IO0xkIKtcCr5wXzV455siJj-oY7MCiuXZe2pjChUlpYSFMI35WDipaGJnuJLVz2uqIiowedXAc9-QottCQ"
    }
  }