$linkedData:
  term: CTPATEIPApplicationCredential
  '@id': https://w3id.org/traceability#CTPATEIPApplicationCredential
title: CTPAT Ecommerce Incentive Program Application Credential
tags:
  - eCommerce
description: >-
    Credential used by Ecommerce participants to register for US CBP CTPAT Ecommerce Incentive Program Certification.
    Issued EIP Credentials are revocable; validity is contingent on ongoing adherence on CTPAT EIP data sharing requirements. 
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - CTPATEIPApplicationCredential
    default:
      - VerifiableCredential
      - CTPATEIPApplicationCredential
    items:
      type: string
      enum:
        - VerifiableCredential
        - CTPATEIPApplicationCredential
  id:
    type: string

  issuanceDate:
    type: string
  issuer:
    $ref: ../snippets/IssuerOrganization.yml
  credentialSchema:
    type: object
    properties:
      id:
        title: Id
        description: The url of the schema file to validate the shape of the json object
        type: string
        format: uri
        example: https://w3id.org/traceability/openapi/components/schemas/credentials/CTPATEIPApplicationCredential.yml
        default: https://w3id.org/traceability/openapi/components/schemas/credentials/CTPATEIPApplicationCredential.yml
        readOnly: true
      type:
        title: Type
        description: The type of validation to be run against the defined schema
        const: OpenApiSpecificationValidator2022
  credentialSubject:
    $ref: ../common/CTPATEIPApplication.yml
  proof:
    type: object
additionalProperties: false
required:
  - '@context'
  - type
  - issuanceDate
  - issuer
  - credentialSubject
example: |-
  {
    "type": [
      "VerifiableCredential",
      "CTPATEIPApplicationCredential"
    ],
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "did:key:z6LSpdSReUHCjYcQb1243aF1vS7sd9ArK585Mm4ktARQxatd",
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "name": "Fulfillment Global, Ltd."
    },
    "issuanceDate": "2022-01-13T09:16:46Z",
    "credentialSubject": {
      "type": [
        "CTPATEIPApplication"
      ],
      "applicant": {
        "type": [
          "Organization"
        ],
        "id": "did:web:ecommerce-fulfillment.example.com",
        "name": "Fulfillment Global, Ltd."
      },
      "applicantType": "Fulfillment"
    }
  }