$linkedData:
  term: ProductRegistrationCredential
  '@id': https://w3id.org/traceability#ProductRegistrationCredential
title: Product Registration Credential
tags:
  - eCommerce
description: >-
  Credential used for Ecommerce Sellers to register listed products.
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - ProductRegistrationCredential
    default:
      - VerifiableCredential
      - ProductRegistrationCredential
    items:
      type: string
      enum:
        - VerifiableCredential
        - ProductRegistrationCredential
  id:
    type: string

  issuanceDate:
    type: string
  issuer:
    $ref: ../common/Organization.yml
  credentialSchema:
    type: object
    properties:
      id:
        title: Id
        description: The url of the schema file to validate the shape of the json object
        type: string
        format: uri
        example: https://w3id.org/traceability/openapi/components/schemas/credentials/ProductRegistrationCredential.yml
        default: https://w3id.org/traceability/openapi/components/schemas/credentials/ProductRegistrationCredential.yml
        readOnly: true
      type:
        title: Type
        description: The type of validation to be run against the defined schema
        const: OpenApiSpecificationValidator2022
  credentialSubject:
    $ref: ../common/Product.yml
  proof:
    type: object
additionalProperties: false
required:
  - '@context'
  - type
  - issuanceDate
  - issuer
  - credentialSubject
example: |-
  {
    "type": [
      "VerifiableCredential",
      "ProductRegistrationCredential"
    ],
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "did:key:z6LSpdSReUHCjYcQb1243aF1vS7sd9ArK585Mm4ktARQxatd",
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "name": "Everything Garden Stuff"
    },
    "issuanceDate": "2022-01-13T09:16:46Z",
    "credentialSubject": {
      "type": [
        "Product"
      ],
      "id": "https://ecommerce-marketplace.example.com/catalog/lawn-flamingos-357fc1f4",
      "gtin": "8948786268509",
      "name": "Lawn Flamingos",
      "description": "Classic plastic lawn flamingos, 2pcs",
      "commodity": {
        "type": [
          "Commodity"
        ],
        "commodityCode": "3926.40.00",
        "commodityCodeType": "HTS",
        "description": "Statuettes and other ornamental articles"
      },
      "productPrice": {
        "type": [
          "PriceSpecification"
        ],
        "price": 98,
        "priceCurrency": "USD"
      },
      "images": [
        "https://ecommerce-marketplace.example.com/catalog/lawn-flamingos-357fc1f4/img/1",
        "https://ecommerce-marketplace.example.com/catalog/lawn-flamingos-357fc1f4/img/2"
      ],
      "seller": {
        "type": [
          "Organization"
        ],
        "id": "did:web:garden-stuff.example.com",
        "name": "Everything Garden Stuff"
      }
    }
  }